/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

#if 0
	__asm volatile ("LDR R1, =#0x20001000");
	__asm volatile ("LDR R2, =#0x20001004");
	__asm volatile ("LDR R0, [R1]");
	__asm volatile ("LDR R1, [R2]");
	__asm volatile ("ADD R0, R0, R1");
	__asm volatile ("STR R0, [R2]");
#endif


//Example 1: Move the content of C variable "val" to ARM register R0
// Instruction  = MOV
// Source       = C variable "val"
// Destination  = R0(ARM core register)

	/* store 'val' in to R0*/
	int val=50;
	__asm volatile("MOV R0,%0": :"r"(val));

//Example 2: Move the content of CONTROL register to C variable "control_reg"
// Instruction  = MRS(CONTROL register is a special register of the ARM core thats why, to read CONTROL register you have to use MRS instruction)
// Source       = CONTROL register
// Destination  = A C variable "control_reg"(OUTPUT operand)

	/*read CONTROL register value in to control_reg variable */
	uint32_t control_reg;
	__asm volatile ("MRS %0,CONTROL" : "=r"(control_reg));

//Example 3: Copy the content of C variable var1 to var2
// Instruction  = MOV
// Source       = A C variable "var1" (INPUT operand)
// Destination  = A C variable "var2" (OUTPUT operand)

	int var1=10, var2;
	__asm volatile("MOV %0,%1":"=r"(var2): "r"(var1));

//Example 3: Copy the contents of pointer into another variable

	/* Read the value present at pointer p2 in to p1 */
	int p1, *p2;
	p2=(int *)0x20000008;

	__asm volatile("LDR %0,[%1]" : "=r"(p1) : "r"(p2) ); //p1 = *p2


    /* Loop forever */
	for(;;);
}









